package final_project;

import java.awt.EventQueue;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

public class ChangeWorker extends JFrame {

	 private Controler controller;
	    private Scanner in;
	    
	    /**
	     * Creates new form RefereeData
	     */
	    public ChangeWorker() {
	        initComponents();
	    }
	    
	    public void setController(Controler controller) {
	        this.controller = controller;
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        previousWorkerDNI = new javax.swing.JTextField();
	        newWorkerDNI = new javax.swing.JTextField();
	        btnCancel = new javax.swing.JButton();
	        btnAccept = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jLabel1.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
	        jLabel1.setText("CHANGE WORKER");

	        jLabel2.setText("Previous Worker DNI");

	        jLabel3.setText("New Worker DNI:");

	        previousWorkerDNI.setText("1111111F");
	        previousWorkerDNI.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                matchCodeActionPerformed(evt);
	            }
	        });

	        newWorkerDNI.setText("2625116F");
	        newWorkerDNI.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                newRefereeDNIActionPerformed(evt);
	            }
	        });

	        btnCancel.setText("Cancel");
	        btnCancel.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnCancelActionPerformed(evt);
	            }
	        });

	        btnAccept.setText("Accept");
	        btnAccept.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnAcceptActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(45, 45, 45)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(btnCancel)
	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(previousWorkerDNI)
	                    .addComponent(newWorkerDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
	                    .addComponent(btnAccept))
	                .addGap(68, 68, 68))
	            .addGroup(layout.createSequentialGroup()
	                .addGap(109, 109, 109)
	                .addComponent(jLabel1)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(26, 26, 26)
	                .addComponent(jLabel1)
	                .addGap(27, 27, 27)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel2)
	                    .addComponent(previousWorkerDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(26, 26, 26)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel3)
	                    .addComponent(newWorkerDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(btnCancel)
	                    .addComponent(btnAccept))
	                .addGap(57, 57, 57))
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	    private void matchCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchCodeActionPerformed
	        // TODO add your handling code here:
	        in = new Scanner(System.in);
	    }//GEN-LAST:event_matchCodeActionPerformed

	    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
	        // TODO add your handling code here:
	        this.controller.backToMenu();
	    }//GEN-LAST:event_btnCancelActionPerformed

	    private void newRefereeDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRefereeDNIActionPerformed
	        // TODO add your handling code here:
	        in = new Scanner(System.in);
	    }//GEN-LAST:event_newRefereeDNIActionPerformed

	    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
	        // TODO add your handling code here:
	        try {
	            this.controller.changeWorkerPitch(newWorkerDNI, previousWorkerDNI);
	            JOptionPane.showMessageDialog(null, "worker changed");
	            this.controller.commit();
	            this.controller.backToMenu();
	        } catch (java.sql.SQLException ex) {
	            JOptionPane.showMessageDialog(null, "Error changing worker");
	            Logger.getLogger(DataBase.class.getName()).log(Level.SEVERE, null, ex);
	            this.controller.backToMenu();
	        }
	    }//GEN-LAST:event_btnAcceptActionPerformed

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Referee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Referee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Referee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Referee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	       
	        }
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new Referee().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JButton btnAccept;
	    private javax.swing.JButton btnCancel;
	    private javax.swing.JTextField previousWorkerDNI;
	    private javax.swing.JTextField newWorkerDNI;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    // End of variables declaration//GEN-END:variables

}
