package final_project;

import java.awt.EventQueue;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

public class DeleteMaterials extends JFrame {

	 private Controler controller;
	    private Scanner in;
	    
	    /**
	     * Creates new form Collaborator
	     */
	    public DeleteMaterials() {
	        initComponents();
	    }
	    
	    public void setController(Controler controller) {
	        this.controller = controller;
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        material_code = new javax.swing.JTextField();
	        bCancelar = new javax.swing.JButton();
	        bAceptar = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jLabel1.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
	        jLabel1.setText("MATERIAL DATA");

	        jLabel2.setText("Material Code");

	        material_code.setText("7777");
	        material_code.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                CIFActionPerformed(evt);
	            }
	        });

	        bCancelar.setText("Cancel");
	        bCancelar.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                bCancelActionPerformed(evt);
	            }
	        });

	        bAceptar.setText("Accept");
	        bAceptar.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                bAcceptActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        layout.setHorizontalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(layout.createSequentialGroup()
	        			.addGap(77)
	        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        				.addGroup(layout.createSequentialGroup()
	        					.addComponent(jLabel1)
	        					.addContainerGap())
	        				.addGroup(layout.createSequentialGroup()
	        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        						.addGroup(layout.createSequentialGroup()
	        							.addGap(8)
	        							.addComponent(bCancelar)
	        							.addPreferredGap(ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
	        						.addGroup(layout.createSequentialGroup()
	        							.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
	        							.addGap(18)))
	        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        						.addComponent(material_code, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
	        						.addGroup(layout.createSequentialGroup()
	        							.addGap(33)
	        							.addComponent(bAceptar)))
	        					.addGap(68))))
	        );
	        layout.setVerticalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(layout.createSequentialGroup()
	        			.addGap(25)
	        			.addComponent(jLabel1)
	        			.addGap(63)
	        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        				.addComponent(jLabel2)
	        				.addComponent(material_code, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
	        			.addPreferredGap(ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
	        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        				.addComponent(bCancelar)
	        				.addComponent(bAceptar))
	        			.addGap(57))
	        );
	        getContentPane().setLayout(layout);

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	    private void CIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIFActionPerformed
	        in = new Scanner(System.in);
	    }//GEN-LAST:event_CIFActionPerformed

	    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
	        this.controller.backToMenu();
	    }//GEN-LAST:event_bCancelarActionPerformed

	    private void bAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
	        try {
	            this.controller.deleteMaterial(material_code);
	            JOptionPane.showMessageDialog(null, "Material deleted");
	            this.controller.commit();
	            this.controller.backToMenu();
	        } catch (java.sql.SQLException ex) {
	            JOptionPane.showMessageDialog(null, "Error deleting material");
	            Logger.getLogger(DeleteMaterials.class.getName()).log(Level.SEVERE, null, ex);
	            this.controller.backToMenu();
	        }
	    }//GEN-LAST:event_bAceptarActionPerformed

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(DeleteCollaborator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(DeleteCollaborator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(DeleteCollaborator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(DeleteCollaborator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new DeleteMaterials().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JTextField material_code;
	    private javax.swing.JButton bAceptar;
	    private javax.swing.JButton bCancelar;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    // End of variables declaration//GEN-END:variables

}
