/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_project;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Color;

/**
 *
 * @author Diego de Luis Ballesteros
 */
public class View extends javax.swing.JFrame {
    private Controler controller;

    /**
     * Creates a new form View
     */
    public View() {
        initComponents();
    
    }

    public void setController(Controler controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        btnShowWorkers1 = new javax.swing.JButton();
        btnChangeReferee = new javax.swing.JButton();
        btnShowWorkers = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnConsultCouples = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDeleteCollaborator = new javax.swing.JButton();
        btnRegisterMaterial = new javax.swing.JButton();

        btnShowWorkers1.setBackground(new java.awt.Color(218, 236, 255));
        btnShowWorkers1.setFont(new java.awt.Font("Farah", 0, 16)); // NOI18N
        btnShowWorkers1.setText("SHOW WORKERS");
        btnShowWorkers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowWorkers1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        btnChangeReferee.setBackground(new java.awt.Color(218, 236, 255));
        btnChangeReferee.setFont(new Font("Dialog", Font.PLAIN, 16)); // NOI18N
        btnChangeReferee.setText("Change referee");
        btnChangeReferee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeRefereeActionPerformed(evt);
            }
        });

        btnShowWorkers.setBackground(new java.awt.Color(218, 236, 255));
        btnShowWorkers.setFont(new java.awt.Font("Farah", 0, 16)); // NOI18N
        btnShowWorkers.setText("Show workers");
        btnShowWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowWorkersActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(218, 236, 255));
        btnExit.setFont(new java.awt.Font("Farah", 1, 16)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.setAlignmentX(0.5F);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnConsultCouples.setBackground(new java.awt.Color(218, 236, 255));
        btnConsultCouples.setFont(new Font("Dialog", Font.PLAIN, 16)); // NOI18N
        btnConsultCouples.setText("Consult couples");
        btnConsultCouples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultCouplesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
        jLabel1.setText("MAIN DATABASE MENU");

        btnDeleteCollaborator.setBackground(new java.awt.Color(218, 236, 255));
        btnDeleteCollaborator.setFont(new java.awt.Font("Farah", 0, 16)); // NOI18N
        btnDeleteCollaborator.setText("Delete collaboration");
        btnDeleteCollaborator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCollaboratorActionPerformed(evt);
            }
        });

        btnRegisterMaterial.setBackground(new java.awt.Color(218, 236, 255));
        btnRegisterMaterial.setFont(new java.awt.Font("Farah", 0, 16)); // NOI18N
        btnRegisterMaterial.setText("Register material");
        btnRegisterMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterMaterialActionPerformed(evt);
            }
        });
        
        btnShowReferees = new JButton("Show referees");
        btnShowReferees.setFont(new Font("Dialog", Font.PLAIN, 16));
        btnShowReferees.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 btnShowRefereesActionPerformed(e);
        	}
        });
        
        btnChangeWorkers = new JButton("Change workers");
        btnChangeWorkers.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnChangeWorkersActionPerformed(e);
        	}
        });
        btnChangeWorkers.setFont(new Font("Dialog", Font.PLAIN, 16));
        
        btnShowCollaborator = new JButton("Show collaboration");
        btnShowCollaborator.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnShowCollaboratorsActionPerformed(e);
        	}
        });
        btnShowCollaborator.setFont(new Font("Dialog", Font.PLAIN, 16));
        
        btnChangeCollaborator = new JButton("Add collaboration");
        btnChangeCollaborator.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 btnInsertCollaborationActionPerformed(e);
        	}
        });
        btnChangeCollaborator.setFont(new Font("Dialog", Font.PLAIN, 16));
        
        btnShowMaterials = new JButton("Show materials");
        btnShowMaterials.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 btnShowMaterialsActionPerformed(e);
        	
        	}
        });
        btnShowMaterials.setFont(new Font("Dialog", Font.PLAIN, 16));
        
        btnDeleteMaterials = new JButton("Delete materials");
        btnDeleteMaterials.setFont(new Font("Dialog", Font.PLAIN, 16));
        btnDeleteMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMaterialsActionPerformed(evt);
            }
        });
        
        
        btnDeleteWorkersIn = new JButton();
        btnDeleteWorkersIn.setText("Delete workers in pitch");
        btnDeleteWorkersIn.setFont(new Font("Dialog", Font.PLAIN, 16));
        btnDeleteWorkersIn.setBackground(new Color(218, 236, 255));
        btnDeleteWorkersIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteWorkers1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(0, 332, Short.MAX_VALUE)
        			.addComponent(btnExit)
        			.addGap(212))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(btnChangeCollaborator, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnChangeWorkers, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnChangeReferee, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnRegisterMaterial, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnConsultCouples, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnShowWorkers, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnShowReferees, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        				.addComponent(btnShowCollaborator, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        				.addComponent(btnShowMaterials, GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnDeleteCollaborator, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        				.addComponent(btnDeleteMaterials, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        				.addComponent(btnDeleteWorkersIn, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(155)
        			.addComponent(jLabel1)
        			.addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(28)
        			.addComponent(jLabel1)
        			.addGap(28)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnChangeReferee)
        				.addComponent(btnShowReferees, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(btnConsultCouples)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnShowWorkers)
        				.addComponent(btnChangeWorkers, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnDeleteWorkersIn, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnShowCollaborator, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnDeleteCollaborator)
        				.addComponent(btnChangeCollaborator, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnRegisterMaterial)
        				.addComponent(btnShowMaterials, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnDeleteMaterials, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
        			.addComponent(btnExit)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);
      
        pack();
        
        
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeRefereeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeRefereeActionPerformed
        this.controller.refereeData();
    }//GEN-LAST:event_btnChangeRefereeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.controller.disconnect();
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnShowWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowWorkersActionPerformed
        this.controller.showTables();
    }//GEN-LAST:event_btnShowWorkersActionPerformed

    private void btnConsultCouplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultCouplesActionPerformed
        this.controller.couplesData();
    }//GEN-LAST:event_btnConsultCouplesActionPerformed

    private void btnShowWorkers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowWorkers1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowWorkers1ActionPerformed

    private void btnDeleteCollaboratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCollaboratorActionPerformed
        this.controller.collaboratorData();
    }//GEN-LAST:event_btnDeleteCollaboratorActionPerformed

    private void btnRegisterMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterMaterialActionPerformed
        // TODO add your handling code here:
        this.controller.materialData();
    }//GEN-LAST:event_btnRegisterMaterialActionPerformed
    private void btnDeleteWorkers1ActionPerformed(java.awt.event.ActionEvent evt){
    	 this.controller.deleteWorkerData();
    }
    private void btnChangeWorkersActionPerformed(java.awt.event.ActionEvent evt) {
    	this.controller.changeWorkerData();
    }
    private void btnShowMaterialsActionPerformed(java.awt.event.ActionEvent evt) {
    	this.controller.showTables();
    }
    private void btnShowCollaboratorsActionPerformed(java.awt.event.ActionEvent evt) {
    	this.controller.showTables();
    }
   
    private void btnShowRefereesActionPerformed(java.awt.event.ActionEvent evt) {
    	this.controller.showTables();
    }

    private void  btnInsertCollaborationActionPerformed(java.awt.event.ActionEvent evt) {
    	this.controller.insertCollaborationData();
    }

    private void  btnDeleteMaterialsActionPerformed(java.awt.event.ActionEvent evt) {
    	this.controller.deleteMaterialData();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeReferee;
    private javax.swing.JButton btnConsultCouples;
    private javax.swing.JButton btnDeleteCollaborator;
    private javax.swing.JButton btnRegisterMaterial;
    private javax.swing.JButton btnShowWorkers;
    private javax.swing.JButton btnShowWorkers1;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private JButton btnShowReferees;
    private JButton btnChangeWorkers;
    private JButton btnShowCollaborator;
    private JButton btnChangeCollaborator;
    private JButton btnShowMaterials;
    private JButton btnDeleteMaterials;
    private JButton btnDeleteWorkersIn;
}

